# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-09 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170709_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduationdetails',
            name='course',
            field=models.CharField(choices=[('bsc', 'B.Sc.'), ('B.E.', 'B.E.'), ('btech', 'B.Tech.'), ('ba', 'B.A.'), ('bcom', 'B.Com.')], max_length=20),
        ),
        migrations.AlterField(
            model_name='graduationdetails',
            name='stream',
            field=models.CharField(choices=[('Information Technology', 'Information Technology'), ('Computer Science', 'Computer Science'), ('Mechanical Engg', 'Mechanical Engg'), ('Electrical Engg', 'Electrical Engg'), ('Electronics and Communication', 'Electronics and Communication'), ('History', 'History'), ('Geography', 'Geography'), ('Economics', 'Economics'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Maths', 'Maths')], max_length=20),
        ),
    ]
