# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170709_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduationdetails',
            name='heading',
            field=models.CharField(default='Graduation', max_length=100),
        ),
        migrations.AddField(
            model_name='intership',
            name='heading',
            field=models.CharField(default='Internships', max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='heading',
            field=models.CharField(default='Jobs', max_length=100),
        ),
        migrations.AddField(
            model_name='projects',
            name='heading',
            field=models.CharField(default='Projects', max_length=100),
        ),
        migrations.AddField(
            model_name='secondarydetails',
            name='heading',
            field=models.CharField(default='Secondary (X)', max_length=100),
        ),
        migrations.AddField(
            model_name='seniorsecondarydetails',
            name='heading',
            field=models.CharField(default='Senior Secondary (XII)', max_length=100),
        ),
    ]
