# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-15 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170711_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduationdetails',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='intership',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='job',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='secondarydetails',
            name='heading',
        ),
        migrations.RemoveField(
            model_name='seniorsecondarydetails',
            name='heading',
        ),
    ]
