# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 10:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_auto_20170717_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(default='', max_length=20)),
                ('organisation', models.CharField(default='', max_length=50)),
                ('duration', models.CharField(default='', max_length=20)),
                ('description', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='intership',
            name='user',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='location',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='role',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='location',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='role',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='job',
            name='year',
        ),
        migrations.DeleteModel(
            name='Intership',
        ),
    ]
